Repository RichardNixon990/SwiftPay, pull requests merged in 2025-02, with the labels that each got.

#30 Update Style + Nambah Form Select Role
  public/assets/Image/loginBG.png
  public/assets/css/siswa/fLanding.css
  public/assets/css/siswa/login.css
  resources/views/page/Login_Register/Login.blade.php
Labels: skill issue

#36 sLanding siswa style
  public/assets/css/siswa/sLanding.css
  resources/views/admin/components/adminNavbar.blade.php
  resources/views/admin/layouts/main.blade.php
  resources/views/admin/page/Dashboard/landing.blade.php
  resources/views/components/navbar.blade.php
  resources/views/page/Dasboard/sLanding.blade.php
Labels: skill issue

#38 Style Management Class
  public/assets/Image/manageClassBG.png
  public/assets/css/admin/manageClass.css
  resources/views/admin/layouts/main.blade.php
  resources/views/admin/page/Dashboard/manageClass.blade.php
  routes/web.php
Labels: enhancement, Not Skill issue

#39 Buat Middleware Auth, Implementasi dashboard
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/SiswaController.php
  app/Http/Kernel.php
  app/Http/Middleware/AuthCheck.php
  public/assets/css/siswa/login.css
  resources/views/admin/components/adminNavbar.blade.php
  resources/views/admin/page/Dashboard/landing.blade.php
  resources/views/components/navbar.blade.php
  resources/views/page/Dasboard/sLanding.blade.php
  routes/web.php
Labels: Not Skill issue

#40 Update Form Tambah Siswa
  database/seeders/DatabaseSeeder.php
  public/assets/css/admin/manageSiswa.css
  resources/views/admin/page/Dashboard/manageSiswa.blade.php
Labels: Not Skill issue

#43 nampilin list kelas, hapus kelas
  app/Http/Controllers/AdminController.php
  database/seeders/DatabaseSeeder.php
  resources/views/admin/page/Dashboard/manageClass.blade.php
  routes/web.php
Labels: Not Skill issue

#45 impleemntasi fitur crud siswa,kelas,spp + sesuain ke viewnya
  .phpunit.result.cache
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/KelasController.php
  app/Models/Siswa.php
  app/Models/Spp.php
  database/migrations/2025_02_03_000003_create_spps_table.php
  database/seeders/DatabaseSeeder.php
  resources/views/admin/page/Dashboard/manageClass.blade.php
  resources/views/admin/page/Dashboard/manageSPP.blade.php
  resources/views/admin/page/Dashboard/manageSiswa.blade.php
  routes/web.php
Labels: enhancement, Not Skill issue

#47 implementasi crud petugas + refactor
  app/Http/Controllers/AdminController.php
  database/factories/SppFactory.php
  database/migrations/2025_02_03_043149_create_siswas_table.php
  database/migrations/2025_02_03_043310_create_pembayarans_table.php
  resources/views/admin/page/Dashboard/managePetugas.blade.php
  resources/views/admin/page/Dashboard/manageSiswa.blade.php
  routes/web.php
Labels: enhancement, Not Skill issue

#49 nambahin text dinamis
  resources/views/admin/components/adminNavbar.blade.php
  resources/views/admin/page/Dashboard/landing.blade.php
  resources/views/admin/page/Dashboard/manageSiswa.blade.php
  resources/views/page/Dasboard/sLanding.blade.php
Labels: enhancement

#51 implementasi pembayaran dan histori dan dashboard admin
  app/Http/Controllers/AdminController.php
  app/Models/Pembayaran.php
  database/factories/SppFactory.php
  database/migrations/2025_02_03_043149_create_siswas_table.php
  database/migrations/2025_02_03_043310_create_pembayarans_table.php
  database/seeders/DatabaseSeeder.php
  resources/views/admin/page/Dashboard/bayarSPP.blade.php
  resources/views/admin/page/Dashboard/landing.blade.php
  routes/web.php
Labels: enhancement

#54 implementasi backend siswa nyesuain data dinamis euy
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/SiswaController.php
  app/Models/Siswa.php
  database/factories/SiswaFactory.php
  database/seeders/DatabaseSeeder.php
  resources/views/admin/page/Dashboard/bayarSPP.blade.php
  resources/views/admin/page/Dashboard/manageSiswa.blade.php
  resources/views/page/Dasboard/sLanding.blade.php
Labels: enhancement, Not Skill issue

#55 fitur laporan pe de ef
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/SiswaController.php
  composer.json
  composer.lock
  resources/views/admin/page/Dashboard/bayarSPP.blade.php
  resources/views/page/Dasboard/sLanding.blade.php
  resources/views/page/pdf/pdf.blade.php
  routes/web.php
Labels: enhancement, Not Skill issue
